### ISSUE TITLE
Handle the libOpenCL.so symlink not being available

### ISSUE THREAD

**Issue by rcombs** [bashbaug/opencl-runtime-loader#19]
Some distros' ICD-loader packages install `libOpenCL.so.1`, but not a symlink in `libOpenCL.so`; on Ubuntu the libOpenCL.so is part of a dev package. I'd suggest trying to open `libOpenCL.so.1`, and if that fails, trying `libOpenCL.so`.

**Comment by bashbaug** [comment]
Good idea.  I suspect it's probably OK to just open `libOpenCL.so.1`, but I agree it's safest to check both.  I'll add this shortly.
